### ISSUE TITLE
Testes Unitários - Memória

### ISSUE THREAD

**Issue by heukirne** [noharm-ai/backend#11]
Desenvolver testes unitários para as funções de Memória da API

/memory/string:kind GET
/memory/int:idMemory PUT

**Comment by heukirne** [comment]
Boa tarde, @asserdna e @rsip22.

Somos uma startup sem fins lucrativos de Porto Alegre. Temos algumas demandas de Python pra uma API que desenvolvemos. Gostaria de contratar alguém pra começar a me ajudar nos testes unitários.
Vocês animam trabalhar nesse projeto ou tem alguma amiga pra indicar?

Abraços!

**Comment by ivanjrju** [comment]
Boa tarde,

Como faço para ser voluntário?

**Comment by heukirne** [comment]
Boa tarde, Ivan!
Pode me mandar um email pra gente marcar uma conversa?
henrique@noharm.ai
Abraços!

**Comment by heukirne** [comment]
Sugestão de Atividade: @caesarcc
